### ISSUE TITLE
Relationship FU Plan: Kathy Krenger

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#138]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by mirichann** [comment]
Hi Kathy,

We wanted to reach out and thank you again for taking the time to participate in our Executive Interview Series. Our conversation allowed us to draw some great advice and stories that we are certain our students will appreciate! Your expertise within communications and your strong advice about the valuable experience you gained from working at a PR agency is going to provide our students with great knowledge as they pursue similar career paths as you! 

Attached is a short clip from your interview that we thought highlighted an amazing story from your career journey. We can't wait to share this story with our students to demonstrate the power of networking and how it landed you your first job.

**Comment by mirichann** [comment]
Hi Kathy,

We wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing (INSERT Q TOPICS). Both the Promazo team and our student audience will be excited to learn from you and your experiences.
Attached is a short clip from the interview that we found particularly interesting. The points you made on (TOPIC) were (Trait).
Again, we thank you for your time and meaningful conversation. We look forward to
