### ISSUE TITLE
Relationship FU Plan: Kunal Anand

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#139]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by mirichann** [comment]
Hi Kunal,

We wanted to reach out and thank you again for taking the time to participate in our Executive Interview Series. Our conversation allowed us to draw some great advice and stories that we are certain our students will appreciate! Your expertise within technology and cyber security and your inspirational, entrepreneurial spirit is going to provide our students with great knowledge and motivation as they pursue similar career paths as you!

Attached is a short clip from your interview that we thought highlighted an amazing lesson you learned after years of working with different companies. We can't wait to share this story with our students to demonstrate the power of versatility and how it allowed you to realize the career path you wanted to focus on.

As mentioned at the end of the interview, we are always looking to expand our interview series and tap into different kinds of career journeys with different executives. We have identified a few of your colleagues as potential career interviewees and would greatly appreciate any contact information or connections you could provide between the two of us.

- William Patrick Opet (Global CISO at JP Morgan Chase Co.)
- Phil Venables (CISO at Google Cloud)
- Adam O'Donnell (Deputy CISO at Stripe)
- Joshua Roth (CTO at Ring)
- Charles Hausmann (CISO at Peloton)
- Andrew Kirkland (Global CISO at Starbucks)

Our students would benefit greatly hearing from any one of these individuals or any other recommendations you may have and we appreciate your support of our mission! We also know you mentioned your Prevoty co-founder at the end of the interview and we think he would be a wonderful interviewee for our Executive Interview Series if there is any connection you can make there.

We would also be thrilled to have you back for a second interview, possibly a joint interview with your Prevoty co-founder to discuss the journey of founding the company and how you as a team, overcame the challenges that come with having your entrepreneurial spirit. We would also love to dive deeper into your personal vision for the future of technology and cybersecurity.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
Miri Chan & Brett Hummel

**Comment by mirichann** [comment]
I need to cut clip.
13:00- 13:16

**Comment by mirichann** [comment]
Relationship Action Plan:
https://docs.google.com/document/d/1vYqEt3MlD6Kx2efB05lWcZtQHcGejt6oMkuQcyAcVlM/edit?usp=sharing
