### ISSUE TITLE
Relationship FU Plan: Scott Lovett

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#141]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by mirichann** [comment]
Hi Scott,

We wanted to reach out and thank you again for taking the time to participate in our Executive Interview Series. Our conversation allowed us to draw some great advice and stories that we are certain our students will appreciate! Your expertise within communications and your strong advice about the valuable experience you gained from working at a PR agency is going to provide our students with great knowledge as they pursue similar career paths as you!

Attached is a short clip from your interview that we thought highlighted an amazing story from your career journey. We can't wait to share this story with our students to demonstrate the power of networking and how it landed you your first job.

As mentioned at the end of the interview, we are always looking to expand our interview series and tap into different kinds of career journeys with different executives. We have identified a few of your colleagues as potential career interviewees and would greatly appreciate any contact information or connections you could provide between the two of us.

Jess Vultagio (VP Marketing & Head of Kithcen @ Kraft Heinz)
Jonathan Adashek (Chief Communications Officer @ IBM)
Katie Boylan (Chief Communications Officer @ Target)
Andre Maciel (Global CFO @ Kraft Heinz)
Melissa Werneck (Global CPO @ Kraft Heinz)
Julia Vander Ploeg (Global Head of Digital & Technology @ Hyatt Hotels)
Our students would benefit greatly hearing from any one of these individuals or any other recommendations you may have and we appreciate your support of our mission!

We would also be thrilled to have you back for a second interview, possibly a joint interview with another CCO to discuss the differences between communication strategies within different companies/ industries. We would also love to dive deeper into your personal vision for the future of communications.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
Miri Chan & Brett Hummel

**Comment by mirichann** [comment]
Need to cut clip - same as short form.
1:15:33- 1:15:59
