### ISSUE TITLE
Relationship FU Plan: Michael Fraccaro

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#143]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by howie-emond** [comment]
Hi, Michael, we wanted to reach out and thank you again for participating in our Executive Interview Series. During our discussion, we had the privilege of hearing about your international career journey, insights into our role as Chief People Officer, Mastercard’s opportunities and future outlook, and the advice you had for students entering the field. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on what both Mastercard and other companies are looking for in new hires today was deeply helpful to our audience. Your words will provide great guidelines for our students.

We are curious to hear if there are any opportunities to conduct similar interviews with some of your colleagues. We have identified the following as potential targets for future interviews: 
Michael Fiore
Jorn Lambert
Ed McLaughlin
Craig Vosburg
Raj Seshadri
Sachin Mehra

Any contacts for these individuals, or other recommendations you may have, would benefit our project immensely.

Also, if you have any time in the future, we would be thrilled to have you on for a second interview, as your input and advice has been greatly appreciated. A discussion which dives further into your personal journey and visions on the industry’s future would be meaningful to our students.

Again, we thank you for your time and meaningful conversation. We look forward to building a closer relationship with you.

**Comment by howie-emond** [comment]
ATTATCHED CLIP
- In Fraccaro Interview folder
- fraccaro-insta.mov

**Comment by howie-emond** [comment]
Future Asks- Profile Links

Michael Fiore
https://www.linkedin.com/in/michaelfiore/

Jorn Lambert
https://www.linkedin.com/in/jorn-lambert-4b01323/

Ed McLaughlin
https://www.linkedin.com/in/ed-mclaughlin-837ba52/

Craig Vosburg
https://www.linkedin.com/in/craig-vosburg-60401811/

Raj Seshadri
https://www.linkedin.com/in/seshadriraj/

Sachin Mehra
https://www.linkedin.com/in/sachin-mehra-8a88775/

**Comment by howie-emond** [comment]
UPDATED MESSAGE

Hi Michael, we wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing about your international career journey, insights into our role as Chief People Officer, Mastercard’s opportunities and future outlook, and the advice you had for students entering the field. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on what both Mastercard and other companies are looking for in new hires today was deeply helpful to our audience. Your words will provide great guidelines for our students.

When your schedule permits, we would love to have you on for a second interview where we can dive further into your journey and insights. Again, we thank you for your time and conversation, and look forward to building a closer relationship with you.

(Same Attached Clip)

**Comment by howie-emond** [comment]
Plan

https://docs.google.com/document/d/1OBZUe-bMYgAxRM8VuxIeUwQYwrW-BZIDqc0jRFODeBM/edit
