### ISSUE TITLE
Relationship FU Plan: Marie Robinson

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#146]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by howie-emond** [comment]
Hi Marie, we wanted to reach out and thank you again for participating in our Executive Interview Series. 

During our discussion, we had the privilege of hearing your views on developing as a leader, moving around in your career, inter-workings of acquisitions and transformations, a new industry dominated by tech and remote work, and so much more. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on viewing changes to move for your job, even to unfavorable locations, as positive opportunities and a chance at greater leadership roles. We thought this would help our students get comfortable with the idea, and benefit them immensely as they move into their careers.

We are curious to hear if there are any opportunities to conduct similar interviews with some of your colleagues. We have identified the following as potential targets for future interviews: 
Aaron Alt
Tom Peck
Kevin Hourican
Judith Sansone

Any contacts for these individuals, or other recommendations you may have, would benefit our project immensely.

Also, if you have any time in the future, we would be thrilled to have you on for a second interview, as your input and advice has been greatly appreciated. A discussion which dives further into your personal journey and visions on the industry’s future would be meaningful to our students.

Again, we thank you for your time and meaningful conversation. We look forward to building a closer relationship with you.

**Comment by howie-emond** [comment]
ATTATCHED CLIP
- In Marie Robinson interview folder
- marie-robinson-follow-up.mov

**Comment by howie-emond** [comment]
Future Asks- Profile Links

Aaron Alt
https://www.linkedin.com/in/aaronalt/

Tom Peck
https://www.linkedin.com/in/tom-peck-0108b9a/

Kevin Hourican
https://www.linkedin.com/in/kevin-hourican-b67a06/

Judith Sansone
https://www.linkedin.com/in/judy-judith-sansone-6999189/

**Comment by howie-emond** [comment]
UPDATED MESSAGE 

Hi Marie, we wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing your views on developing as a leader, moving around in your career, inter-workings of acquisitions and transformations, a new industry dominated by tech and remote work, and so much more. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on viewing changes to move for your job, even to unfavorable locations, as positive opportunities and a chance at greater leadership roles. We thought this would help our students get comfortable with the idea, and benefit them immensely as they move into their careers.

When your schedule permits, we would greatly appreciate a 15 minute discussion to introduce our mentorship program, which we we believe your involvement would benefit greatly. Again, we thank you for your time and meaningful conversation, and we look forward to building a closer relationship with you.

SAME CLIP

**Comment by howie-emond** [comment]
Plan

https://docs.google.com/document/d/1FaBEdUAm5u-EG2BbzP16aLEwB140aaN-zl6LWwt4g6I/edit
