### ISSUE TITLE
Relationship FU Plan: Brad Burnham

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#148]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by carolineradke** [comment]
Hi Brad, we wanted to reach out and thank you again for participating in our Executive Interview Series. 

During our discussion, we had the privilege of hearing your perspective on the value of a liberal arts education and starting from first principles is something that is built up over years and years. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on leveraging the critical thinking skills and curiosity you had from whatever field you come from were interesting as you talked about how hard skills can oftentimes be learned on the job.

We thank you for your time and meaningful conversation. We look forward to staying in contact with you.

**Comment by carolineradke** [comment]
ATTACHED CLIP:

6:32-6:59

**Comment by carolineradke** [comment]
https://docs.google.com/document/d/1k1adrafUXHuukhy3wo9dhhQlk_bE2eSNI1dEk8rsmC8/edit

Plan
