### ISSUE TITLE
Relationship FU Plan: Peter Wang

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#149]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by George-Liu3** [comment]
Hi Peter, we wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing about how your experience building Mozar, your first entrepreneurial endeavor, while engaging also working at the Bank of New York Mellon and how these experiences taught you invaluable lessons for both worlds. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

The point you highlighted that, “When you have two paths going, it puts both paths in perspective. Something to compare the other against,” will provide our students with meaningful insight into how they might travel down their own career paths.

We are curious to hear if there are any opportunities to conduct similar interviews with some of your colleagues. We have identified the following as potential targets for future interviews:

Rupa Athreya
Aparna Ramaswamy
Jason Seats
Kimberly Smith

Any contacts for these individuals, or other recommendations you may have, would benefit our project immensely.

Also, if you have any time in the future, we would be thrilled to have you on for a second interview, as your input and advice has been greatly appreciated. A discussion which dives further into your personal journey and visions on the industry’s future would be meaningful to our students.

Again, we thank you for your time and conversation. We look forward to building a closer relationship with you.

**Comment by George-Liu3** [comment]
Contacts: 
Christian Baesler
https://www.linkedin.com/in/christianbaesler/

Dao Nguyen
https://www.linkedin.com/in/daonguyen/

Rhonda Powell
https://www.linkedin.com/in/rhonda-powell-b457131/

**Comment by George-Liu3** [comment]
Hi Peter, we wanted to reach out and thank you again for participating in our Executive Interview Series.

We are curious to hear if there are any opportunities to conduct similar interviews with some of your colleagues. We have identified the following as potential targets for future interviews:

Christian Baesler
Dao Nguyen
Rhonda Powell

Any contacts for these individuals, or other recommendations you may have, would benefit our project immensely.

Also, if you have any time in the future, we would be thrilled to have you on for a second interview, as your input and advice has been greatly appreciated. A discussion which dives further into your personal journey and visions on the industry’s future would be meaningful to our students.

Again, we thank you for your time and conversation. We look forward to building a closer relationship with you.
