### ISSUE TITLE
Relationship FU Plan: Brooklyn Bridge Ventures

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#150]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by George-Liu3** [comment]
Hi Charlie, we wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing about how your experiences experimenting and discovering the right career and firm fit, your advice towards risk taking and its potential rewards, and how students can better reach out towards mentors for advice. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

The point you highlighted that "there is a lot of pressure to pick an end goal in career search, something that many have very little information on" and how only through experimentation can a young professional understand if a particular career at a particular firm interests them, will provide our students with meaningful insight into how they might travel down their own career paths and how they approach career planning.

**Comment by George-Liu3** [comment]
Hi Charlie, we wanted to reach out and are curious to hear if there are any opportunities to conduct similar interviews with you in the future.

If you have any time in the future, we would be thrilled to have you on for a second interview with fellow executives and venture capitalists, as your input and advice has been greatly appreciated. A discussion which dives further into your visions on the New York City entrepreneurial space. Your advice and unique perspective would be meaningful to our students.

Again, we thank you for your time and conversation. We look forward to building a closer relationship with you.
