### ISSUE TITLE
Relationship FU Plan: Koen Deryckere

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#156]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by howie-emond** [comment]
Hi Koen, we wanted to reach out and thank you again for participating in our Executive Interview Series. 

During our discussion, we had the privilege of hearing about how you found your career path, your view on the future for young consultants, a rapidly expanding usage of tech in business, and the inter-workings of the Accenture workplace. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you highlighted regarding how Accenture’s culture operates will provide our students with meaningful insight.

We are curious to hear if there are any opportunities to conduct similar interviews with some of your colleagues. We have identified the following as potential targets for future interviews: 
Paul Daugherty
KC McClure
Kris Timmermans
Manish Sharma
Emma McGuigan

Any contacts for these individuals, or other recommendations you may have, would benefit our project immensely.

Also, if you have any time in the future, we would be thrilled to have you on for a second interview, as your input and advice has been greatly appreciated. A discussion which dives further into your personal journey and visions on the industry’s future would be meaningful to our students.

Again, we thank you for your time and meaningful conversation. We look forward to building a closer relationship with you.

**Comment by howie-emond** [comment]
ATTATCHED CLIP
- In linked folder
- koen-follow-up.mov

https://drive.google.com/drive/folders/15PJIVzcgGohM1O0S71_1YBvnVna6zsmY?usp=sharing

**Comment by howie-emond** [comment]
Future Asks- Profile Links

Paul Daugherty
https://www.linkedin.com/in/paul-r-daugherty/

KC McClure
https://www.linkedin.com/in/kc-mcclure-71660ab4/

Kris Timmermans
https://www.linkedin.com/in/kris-timmermans-209800/

Manish Sharma
https://www.linkedin.com/in/manish-sharma-bbb1a1/

Emma McGuigan
https://www.linkedin.com/in/emmatmcguigan/

**Comment by howie-emond** [comment]
UPDATED MESSAGE

Hi Koen, we wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing about how you found your career path, your view on the future for young consultants, a rapidly expanding usage of tech in business, and the inter-workings of the Accenture workplace. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you highlighted regarding how Accenture’s culture operates will provide our students with meaningful insight.

Again, we thank you for your time and conversation. We look forward to building a closer relationship with you.

(Same Clip)

**Comment by howie-emond** [comment]
Plan

https://docs.google.com/document/d/12bVUFRHKLY8z8arL3mhyAgbvQKhJhAHjc4Ci9J4A4hQ/edit
