### ISSUE TITLE
FU Plan: Invesco-Donie Lochan

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#174]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by howie-emond** [comment]
Hi Donie, we wanted to reach out and thank you again for participating in our Executive Interview Series. 

During our discussion, we had the privilege of hearing your views on opportunities and experience seeking, ways to prepare for new tech trends, digital assets and AI, workplace culture, and so much more. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you made on the importance of cryptocurrencies and new kinds of digital assets will give our students a key insight as they enter the field.

As we closed off the interview, we discussed then possibility of bringing you on for a second interview. When your schedule permits, we would greatly appreciate another session where we can dive deeper into your advice and insights. 

Again, we thank you for your time and meaningful conversation, and look forward to building a closer relationship with you.

**Comment by howie-emond** [comment]
CLIP

A: 28:38(Uh)-28:56(class), 29:36(Um)-29:52(that)

Same as one the first short post on finance, crypto, digital assets, and how it will affect the greater industry.

**Comment by howie-emond** [comment]
Future contacts

Martin L Flanagan - CEO
(no linkedin)

Greg McGreevey - Senior Managing Director, Investments
https://www.linkedin.com/in/greg-mcgreevey-33a173231/

Allison Dukes - CFO
https://www.linkedin.com/in/allison-dukes-28a0252/

Colin Meadows - FORMER Head of Digital Ventures (now at o15, could still be a great connect)
https://www.linkedin.com/in/colin-meadows/

Other non-Invesco?

**Comment by howie-emond** [comment]
Plan

https://docs.google.com/document/d/1e_qtfbEl7Vp74v-XDYc-YC4pP1ghIz8up5kyKxWwudM/edit
