### ISSUE TITLE
FU Plan: TechStars-Matt Kozlov

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#175]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by George-Liu3** [comment]
Hi Matt, 

We wanted to reach out and thank you again for participating in our Executive Interview Series.

During our discussion, we had the privilege of hearing about how your experience as a mentee, and mentor shaped your career journey from starting Techstars LA and breaking into the space industry with no technical expertise to your life long love for mentorship. Both the Promazo team and our student audience will be excited to learn from you and your experiences.

Attached is a short clip from the interview that we found particularly interesting. The points you highlighted regarding how young professionals should navigate finding new and keeping connected with previous mentors.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
George Liu & Brett Hummel

**Comment by George-Liu3** [comment]
Attached Below is FU Clip:

https://drive.google.com/file/d/1Q0zCy4MNJ_UzNE4QRAPqRKaIWuqHZ4tB/view?usp=sharing

**Comment by George-Liu3** [comment]
Hi Matt, 

Our students would benefit greatly from hearing any one of these individuals or any other recommendations you may have and we appreciate your support of our mission!

Forrest Hobbs (Operating Partner @ Kayne Anderson Capital Advisors)
Ian Rogers (Chief Experience Officer @ Ledger)

If you have any time in the future, we would also be thrilled to have you on for a second interview with fellow executives and venture capitalists, as your input and advice has been greatly appreciated. A discussion which dives further into your  visions on the aerospace or healthcare industry’s future developments and how their applications can be applied to existing industries. Your advice and unique perspective would be meaningful to our students.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
George Liu & Brett Hummel
