### ISSUE TITLE
Relationship FU Plan: Imperva-Nanhi Singh

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#177]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by mirichann** [comment]
Hi Nanhi,

We wanted to reach out and thank you again for taking the time to participate in our Executive Interview Series. Our conversation allowed us to draw some great advice and stories that we are certain our students will appreciate! Your advice on how you navigated your first technology job from a finance and accounting background is going to inspire so many students. We are so excited to share your stories and advice with our student audience!

Attached is a short clip from your interview that we thought highlighted an important tip for students who are just beginning their career journeys. We can't wait to share this piece of advice with our students to encourage them to explore different career paths and industries before settling down into a career!

As mentioned at the end of the interview, we are always looking to expand our interview series and tap into different kinds of career journeys with different executives. We have identified a few of your colleagues as potential career interviewees and would greatly appreciate any contact information or connections you could provide between the two of us.

Our students would benefit greatly from hearing any one of these individuals or any other recommendations you may have and we appreciate your support of our mission!

- Sunil Seshadri (CISO @ Wells Fargo)
- Sheila Jordan (Chief Digital Technology Officer @ Honeywell)
- Taylor Nguyen (Global Head of Creative Experiences @ Google)

We would also be thrilled to have you back for a second interview, possibly a joint interview with another CCO or Imperva executive to discuss the differences between customer strategies or how your departments tackle issues. We would also love to dive deeper into your personal vision for the future of customer relationship building and cybersecurity.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
Miri Chan & Brett Hummel

**Comment by mirichann** [comment]
Clip to attach (short form):
A: 11:23- 12:23
