### ISSUE TITLE
Relationship FU-Jenny Abramson

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#201]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by George-Liu3** [comment]
Hi Jenny,

We wanted to reach out and thank you again for taking the time to participate in our Executive Interview Series. Our conversation allowed us to draw some great advice and stories that we are certain our students will appreciate! Your stories and data about the gender gap in the venture capital and entrepreneurship space will bring awareness and inspire many students. We are so excited to share your stories and advice with our student audience!

Attached is a short clip from your interview that we thought highlighted the gender gap in venture capital firms and what factors are driving increasing diversity in these firms. We can't wait to share this eyeopening data with our students to bring more awareness to this issue and how our future generation of professionals can work towards mending the gender gap.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
George Liu & Brett Hummel

**Comment by George-Liu3** [comment]
Attached Clip:
07:09-08:29
(1:20 Minutes)
