### ISSUE TITLE
Venture Capital Contact Pulls

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#203]
**User Story / Problem / Details**
ProMazo wants to build relationships with the investment community and have those connections solidly established as we continue to establish the company in the higher education/HR Tech space.

**Technical Definition of Done**
90 Contacts who are from a target company and have the titles Managing Partner, Partner, Principal with an occasional Head of Communications/Platform or Associate if we think they are very closely aligned with what we are trying to accomplished should be entered in our VC Outreach Google Sheet. Along with pulling their information, we will create a specific customization for each contact that will fit with our email template.

**Definition of Ready**
Brett reviews the contacts, the contact information and customizations and determines that the information was entered correctly for each of the contacts and that the personalizations are sufficiently customized.

**Process**
- [ ] Identify the target company(ies)
- [ ] Identify the types of people you want to target
- [ ] Use Hunter, RocketReach and other tools to ID the potential email
- [ ] Enter the contact's information in the sheet
- [ ] Create customizations/personalizations for the contact's email

**Comment by George-Liu3** [comment]
90
