### ISSUE TITLE
RFP-Jeff Walsh (Intel)

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#211]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by mirichann** [comment]
Hi Jeff,

We wanted to reach out and thank you again for taking the time to participate in our Executive Interview Series. Our conversation allowed us to draw some great advice and stories that we are certain our students will appreciate! Your advice about how to display yourself as a dedicated engineer within your field is going aid so many students as they begin their career journeys.  We are so excited to share your stories and advice with our student audience!

Attached is a short clip from your interview that we thought highlighted an important tip for students with upcoming career interviews. We can't wait to share this niche interview tip with our students to demonstrate the power of demonstrating your skills and prepare them for future job or internship interviews.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
Miri Chan & Brett Hummel

**Comment by mirichann** [comment]
Clip to attach (his short form clip):
A: 23:56- 24:41
