### ISSUE TITLE
RFP-Emily Nordquist (1871)

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#213]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by George-Liu3** [comment]
Hi Emily,

We wanted to reach out and thank you again for taking the time to participate in our Executive Interview Series. Our conversation allowed us to draw some great advice and stories that we are certain our students will appreciate! Your advice about reaching out and raising your hand to grasp any opportunity even when you have to leave your comfort zone will inspire many of our students. We are so excited to share your stories and advice with our student audience!

Attached is a short clip from your interview that we thought highlighted an important tip for students talking to their managers about a job role not being the right fit, while not seeming forceful. We can't wait to share this advice with our students to demonstrate the power of being patient.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
Brett Hummel

**Comment by George-Liu3** [comment]
Attached Clip:
20:40-21:17 & 22:14-22:32 (55 Seconds)
