### ISSUE TITLE
RFP-Jasmine Hoffman (Tech United)

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#219]
**User Story / Problem / Details**
The Content Editor is in charge of ensuring the initial relationship we foster with an interviewee does not decay over time for interviewees that we designate as important. As a result we want to follow a process that allows us to interact and build a relationship with the interviewee over time. The final step of the process should be focused on how connect with an interviewee over multiple interactions and over the course of a year.

**Technical Definition of Done**
Complete all steps in the process

**Definition of Ready**
All of the steps in the process have been approved by Brett 

**Process**
- [ ] Review the interview in its entirety 
- [ ] Thank you note to the participant
- [ ] Quick clip (30s) that shows the interviewee some of the raw footage/a particularly interesting part of the discussion
- [ ] ID potential contacts
- [ ] Formulate ask
- [ ] Create a Relationship Action Plan

**Comment by George-Liu3** [comment]
Hi Jasmin,

We wanted to reach out and thank you again for taking the time to participate in our Executive Interview Series. Our conversation allowed us to draw some great advice and stories that we are certain our students will appreciate! Your advice about being a proactive problem solver, by bring up an issue along with a potential solution, is going aid so many students as they begin their career journeys. We are so excited to share your stories and advice with our student audience!

Attached is a short clip from your interview that we thought highlighted your advice well. We can't wait to share this advice with our students to demonstrate the proactive nature of a great problem solver and how they can begin cultivating these abilities as soon as possible.

Once again, we thank you so much for taking the time to speak with us and supporting our mission for students. We look forward to continuing this relationship with you and your colleagues!

Warm regards,
George Liu & Brett Hummel

**Comment by George-Liu3** [comment]
Attached Clip: 
13:56-15:09 & 15:38-16:00 (1:35 Minutes)
