### ISSUE TITLE
Workforce Updated Deck DUE: 8/18

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#311]

**Comment by jaahmuhl** [comment]
Link: https://docs.google.com/presentation/d/1-TZd7pl_uN4fxoM_xVQ5HqYitFciqt7WttH-nd6gGdw/edit#slide=id.p

**Comment by jaahmuhl** [comment]
- [ ] Slide 10

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVljIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c29795ab8ae2e7ada473fc45146a7e5f02480935/2023-08-19_10-18-47.png)

**Comment by jaahmuhl** [comment]
- [ ] Slide 11

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWNjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0b017594f30c6cc52a692978606825ed27b2c6a3/2023-08-19_10-19-42.png)

**Comment by jaahmuhl** [comment]
- [ ] Slide 14

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWdjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a18e001563821f826908be817335a75952924ec3/2023-08-19_10-28-30.png)

**Comment by MufasaAmir** [comment]
edits done

**Comment by jaahmuhl** [comment]
Slide 10:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0k5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bd21b0df39b547b7beef173e6ccf165498b6aa59/2023-08-25_13-07-19.png)
