### ISSUE TITLE
Neiman Marcus Deck DUE: 8/16

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#313]

**Comment by jaahmuhl** [comment]
Deck Link: https://docs.google.com/presentation/d/1W5mMOEvVgs6rpdNnzRA9qNXzU-FLYWBzo9_EW24uBK4/edit#slide=id.g267fc26d593_0_15

**Comment by MufasaAmir** [comment]
Updates Done

**Comment by jaahmuhl** [comment]
- [ ] Slide 10

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaU1jIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--10acf01e6aa202171c5416ff9528227dceed3f56/2023-08-19_10-18-47.png)

**Comment by jaahmuhl** [comment]
- [ ] Slide 11
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVFjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--284012d79cf1d701050ab2e435846c35a2391ffc/2023-08-19_10-19-42.png)

**Comment by jaahmuhl** [comment]
- [ ] Slide 14

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVVjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1870d9bd5f41dc3bc7d5bc5ff9fdd17f84fadaa5/2023-08-19_10-28-30.png)

**Comment by jaahmuhl** [comment]
- [ ] Slide 17

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaWtjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ffedb18f5972792245e0ef39eced138967b3287b/2023-08-19_10-14-31.png)

**Comment by MufasaAmir** [comment]
edit completed

**Comment by jaahmuhl** [comment]
Slide 17

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdU05IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--07b2c9209766120e04d4ba11bde3007cbc4a4b97/2023-08-25_09-37-32.png)

**Comment by jaahmuhl** [comment]
Slide 18:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdDg5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6bd9fe0b8053256a869d22cb946ac4df69c46297/2023-08-25_09-34-52.png)

**Comment by MufasaAmir** [comment]
done
