### ISSUE TITLE
VXN Shirts DUE: 8/15

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#314]

**Comment by jaahmuhl** [comment]
- [ ] VXN Logo Large with New York City Cursive
- [ ] VXN Logo Large with NYC below (different fonts)
- [ ] VXN Logo Small in top right with NYC and New York City underneath (different fonts)
- [ ] VXN Logo Large with silhouette of skyline and New York City underneath (different fonts)

**Comment by MufasaAmir** [comment]
1. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcThTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5821eaa365e8b94e7003bde79e3c417114961a24/image.png)

2. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckFTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1b573ef939569a2d3704c921a90e4d9e96eb727e/image.png)

3. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0FTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c1d53c538dbadf699c42b829244704f90b1327ae/image.png)

4. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc2dTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5658cfeeead0e06295a25442eb1be87b26015423/image.png)

(Updates are all in the top right)

**Comment by MufasaAmir** [comment]
i emailed the file to you

**Comment by MufasaAmir** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa29UIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ecbe9b9af096412409e8c812a65909c0cdeaa173/image.png)
[Private Zenhub Image]
(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3NUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--318bcb033ae6444a7f0b42d0d34eb5fafcb5d9d4/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBa3dUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5909649e4d5932a693d069139a86db95949b5cd6/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazRUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4258fc2751ff7333f9311bcf492ae925fff9b348/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBazhUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--08ee9e38fe329871753c3b97abb9658a7a04af5f/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbEVUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--de412f1698e4381cc52865aabc43c1260c90a208/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbElUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--285a2ef7e60dd1e5bfce9e90292d6773814c7ab4/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbE1UIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--52a30420f3edd7e5dae9425b5619f086cfea9fb3/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFVUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7b6da36136722035d3b8030ce9f5d3a34505e9be/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbFlUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ccf6749202e6a9a2864142b079edfbc029c4f03c/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGdUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a4170feaa15eb887b2e5fda95c3c15b6788717b4/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbGtUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bc83fb9d8b550e092467f2e5a5be78c3a8598c22/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDRUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--63bb72b3cf644526a130bbee25a9260775a01ff2/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbDhUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--74048bbda13aa39bda7ed32fb0b79812578ad6ad/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUFUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--f74376288511a7d4b72c002f82f9ab2545be3186/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUVUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--bf70cf20ef70a8358779468592d67ebc6a3344a8/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVFUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5dea1cf0c3f3d585c2e6b52e9467dcd22d4abf48/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVVUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d53e66168c5601d73726e3d275cee1633e33e8b1/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVlUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--02a6ff14c48aa0317298713b260f2d4af3950545/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbWtUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a27799ec612e53d2166c2cbe4784656ecb7f154a/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXNUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8eae0b5868871320d2f0f54aa47e7c3f74168b56/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbXdUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--80e48deef7f7e02d5f29f19d58ebf4adee9c0d30/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTBUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--86380c4a42563d9655138c1c7127ce0e71e8e1a1/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbTRUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d6b4d5468c7dbf8caae2bc175127b0ef83f0fef4/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbThUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--87b3ceb7b6ecffd4f727426a578fd209ba9f3608/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkFUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aad7c396c53028babe8f46e4bf5182d6cb23ed41/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkVUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4b7cf2f6f8f59c2510131af5f6a6af97eb57c673/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbklUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1d4332b7318a449c4cb844b2eeddc970bfa40172/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblFUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1bbb749dcab50d3d78ea8c5a332ac934e884f5e3/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbllUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--7e9d5f759abbec7c5fa1eb6461c9c2a5fe77598d/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmNUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2afbd37c4e4c52251d0995cd9d0d21c41d715cf3/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmdUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--0803e288d7f3c6e146a356959f9ba82faad17ec8/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmtUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d6fee35271ed47d565b2ee3a02c6819d5090d8a0/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbm9UIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a4149293bbcdaee8c8ef85aa8de2d4121f9ff0a9/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbnNUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--234f4b9f1e5bdbf302eddb5e026a42c26c5c196a/image.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbndUIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d680f30272b35b97a9f6c8fd6a905d8cd1902a9/image.png)
