### ISSUE TITLE
Email Template  DUE: 8/15

### ISSUE THREAD

**Issue by jaahmuhl** [promazo/100k-Mentor-Challenge-Outreach#317]

**Comment by jaahmuhl** [comment]
- [x] Desktop
- [x] Mobile

**Comment by MufasaAmir** [comment]
fixed mobile view

**Comment by MufasaAmir** [comment]
[existing-invite-template-mobile-fix_2023-08-30T142828.427351.zip](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBaVJTIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--e12ac705f5b6a37e46035f601c6ea4433e148f18/existing-invite-template-mobile-fix_2023-08-30T142828.427351.zip)
[Uploading... non-existing-invite-template-mobile-fix-fixed-steps_2023-08-30T142750.996216.zip]

**Comment by MufasaAmir** [comment]
https://drive.google.com/drive/folders/17K-XZriUT-7dqgI2UhD1ZfNbx4YN3MHP?usp=drive_link
