### ISSUE TITLE
Video Interview-BMO Harris-Fellicia Foster

### ISSUE THREAD

**Issue by carolineradke** [promazo/100k-Mentor-Challenge-Outreach#73]
User Story / Problem / Details
ProMazo wants to develop content that can help students discover their career path/get advice from leaders in business. However, we know that students have short attention spans and we need to develop content that quickly catches them. We also want to make sure the interviewee looks good too so for the LinkedIn post we will be highlighting them/their company as a main focus of that post.

Technical Definition of Done
The video will be cut into the top highlights of the interview, forming a series of clips: Short (for Instagram/Tik Tok that should be around 90 seconds), Medium (for LinkedIn that is around 5-8 minutes) and Long (the 15-30 second introduction for the Podcast). The clips should show the timestamps for the questions and answers of the interviewer/interviewee. 

The editor will also be in charge of developing the styling of the video for the short and medium form (how should we show it on Instagram/Tik Tok/LinkedIn) and creating a blurb that will appear as the caption for the post.

Definition of Ready
Brett reviews the suggested timestamp and blurb for the video and approves it

Process

 Identify the target company(ies)
 Identify the types of people you want to target
 Use Hunter, RocketReach and other tools to ID the potential email
 Enter the contact's information in the sheet
 Create customizations/personalizations for the contact's email

**Comment by jaahmuhl** [comment]
We need to do the blurb for the long form intro with hashtags

**Comment by jaahmuhl** [comment]
I'd also like to see a more engaging intro for the long form
